### PR TITLE
Feature gladwin

### PR DESCRIPTION
**Pull request by gladwin-jft**
1)Get Student Information based on marks greater than a value provided by the user in the Api.
2) Get Teacher by entering Subject name in the Api.

### CODE REVIEW

**Comment by jaineetsingh-jft** [comment]
Please resolve conflicts

**Review by jaineetsingh-jft — CHANGES_REQUESTED** [review]
Please resolve conflicts

**Comment by gladwin-jft** [comment]
@jaineetsingh-jft resolved conflicts, please check.

**Comment by gladwin-jft** [comment]
Changes made in Student and Subject controller

**Review by gladwin-jft — COMMENTED** [review]
Changes made in Subject and Student Controller

**Comment by gladwin-jft** [comment]
Made changes to both student & subject controllers, now both use responseDTO.

**Pull request closed without merging**
